-- AI Job Log Hardening Migration
-- Adds new AiJobType values, DEAD_LETTERED status, and timing/dedup fields to AiJobLog

-- Add new AiJobType enum values
ALTER TYPE "AiJobType" ADD VALUE IF NOT EXISTS 'FEEDBACK_EMBEDDING';
ALTER TYPE "AiJobType" ADD VALUE IF NOT EXISTS 'CIQ_SCORING_FEEDBACK';
ALTER TYPE "AiJobType" ADD VALUE IF NOT EXISTS 'CIQ_SCORING_THEME';
ALTER TYPE "AiJobType" ADD VALUE IF NOT EXISTS 'CIQ_SCORING_ROADMAP';
ALTER TYPE "AiJobType" ADD VALUE IF NOT EXISTS 'CIQ_SCORING_DEAL';
ALTER TYPE "AiJobType" ADD VALUE IF NOT EXISTS 'SUPPORT_SPIKE_DETECTION';
ALTER TYPE "AiJobType" ADD VALUE IF NOT EXISTS 'SURVEY_INTELLIGENCE';
ALTER TYPE "AiJobType" ADD VALUE IF NOT EXISTS 'CUSTOMER_SIGNAL_AGGREGATION';

-- Add DEAD_LETTERED to AiJobStatus enum
ALTER TYPE "AiJobStatus" ADD VALUE IF NOT EXISTS 'DEAD_LETTERED';

-- Add timing and dedup fields to AiJobLog
ALTER TABLE "AiJobLog"
  ADD COLUMN IF NOT EXISTS "startedAt"   TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "durationMs"  INTEGER,
  ADD COLUMN IF NOT EXISTS "attempts"    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "dedupeKey"   TEXT;

-- Add index on dedupeKey for fast idempotency lookups
CREATE INDEX IF NOT EXISTS "AiJobLog_dedupeKey_idx" ON "AiJobLog"("dedupeKey");
